[package]
name = "astro-swarm"
authors = ['only me lol']
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
noise = "0.9"
color-eyre = "0.6.3"
rand = "0.9.1"
chrono = "0.4.40"
log = "0.4.27"
fern = "0.7.1"