name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * SAT" # Weekly checks 🫡

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format Check
        run: cargo fmt --check --all

      - name: Clippy Lint (warnings only)
        run: cargo clippy --all-targets --all-features --no-deps || true

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  taplo-check:
    name: Check TOML files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install taplo-cli
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: Taplo Format Check
        run: taplo fmt --check
